# Project: GetMeMyFruit
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = GetMeMyFruit.o mappyal.o
LINKOBJ  = GetMeMyFruit.o mappyal.o
LIBS     = -L"D:/Useful Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc "../../../Useful Programs/Dev-Cpp/MinGW64/lib/liballegro-4.4.2-md.a" -m32
INCS     = -I"D:/Useful Programs/Dev-Cpp/MinGW64/include" -I"D:/Useful Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Useful Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Useful Programs/Dev-Cpp/MinGW64/include" -I"D:/Useful Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Useful Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Useful Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = GetMeMyFruit.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

GetMeMyFruit.o: GetMeMyFruit.c
	$(CC) -c GetMeMyFruit.c -o GetMeMyFruit.o $(CFLAGS)

mappyal.o: mappyal.c
	$(CC) -c mappyal.c -o mappyal.o $(CFLAGS)
